module.exports = {
  ADMIN_INFO: 'ADMIN_INFO',
  CURRENT_ACTIVE_MENU: 'CURRENT_ACTIVE_MENU',
  JX_TOKENINFO: 'JX_TOKENINFO',
  HISTORY_SEARCH: 'HISTORY_SEARCH',
  FIRST_SEARCH: 'FIRST_SEARCH',
  CURRENT_ITEM: 'CURRENT_ITEM',
  X_TOTAL_COUNT: 'x-total-count'
};
