export default {
  SET_WINDOW_SIZE: 'SET_WINDOW_SIZE',
  SET_IFRAMEURL: 'SET_IFRAMEURL',
  SET_BASE_CONFIG: 'SET_BASE_CONFIG',
  SET_COPYRIGHT: 'SET_COPYRIGHT',
  SET_LOADING: 'SET_LOADING',
  SET_ENLARGEIMG: 'SET_ENLARGEIMG',
  TOGGLE_WARN: 'TOGGLE_WARN',
  JUDGE_IS_OUT_SIGN: 'JUDGE_IS_OUT_SIGN'
};
